site_name: EXPL NIT-C
site_url: https://cliford.net/expl-docs/
site_description: Compiler Lab website for NIT Calicut

theme:
  name: material
  logo: img/nitc-logo.png
  custom_dir: overrides
  palette:
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: purple
        toggle:
          icon: material/lightbulb-outline
          name: Switch to dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: purple
        toggle:
          icon: material/lightbulb
          name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/silcnitc
    - icon: fontawesome/brands/google
      link: https://groups.google.com/g/expl-users

extra_css:
  - extra.css

copyright: >-
  <a rel="license" href="https://creativecommons.org/licenses/by-nc/4.0/">
    <img alt="Creative Commons License" style="border-width:0" src="https://licensebuttons.net/l/by-nc/4.0/80x15.png" />
  </a>
  National Insititute of Technology, Calicut

plugins:
  - search
  - minify:
      minify_html: true

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

INHERIT: nav.yml
